language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install black

services:
  - mongodb

before script:
  - sleep 15
  
script:
  # - black ./ --line-length 120 --check -> unexpectedly failing right now
  - pytest
